version: '3.8'
services:
  vue:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - 8080:8080
    volumes:
      - './:/app'
    command: /bin/sh -c "npm install; npm run serve"
